name: CD Pipeline to AWS (Staging and Production)

on:
  push:
    branches:
      - staging

  workflow_dispatch:

  release:
    types:
      - published

env:
  PORT: 5001
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup, Test, and Build Project

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    name: Authenticate, Build Docker Image, Push to ECR, and Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

      - name: Tag Docker Image
        run: |
          docker tag ${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Push Docker Image to Amazon ECR
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Production (App Runner)
        if: github.event_name == 'release' && github.event.action == 'published' && github.event.release.target_commitish == 'main'
        run: |
          aws apprunner start-deployment \
            --service-arn ${{ secrets.APP_RUNNER_PRODUCTION_ARN }}

      - name: Deploy to Staging (App Runner)
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "Deploying to staging environment"

          aws apprunner start-deployment \
            --service-arn ${{ secrets.APP_RUNNER_STAGING_ARN }}